### ISSUE TITLE
issue with building

### ISSUE THREAD

**Issue by SolarAquarion** [etoile/Etoile#6]
This is gnustep-make 2.6.7. Type 'make print-gnustep-make-help' for help.
Making all in Bootstrap ...
Making all in UnitKit ...
Making build-headers for framework UnitKit...

Build Project: UnitKit

Making all for framework UnitKit...
 Compiling file FrameworkSource/UKTestHandler.m ...
In file included from FrameworkSource/UKTestHandler.m:22:
In file included from FrameworkSource/UKTestHandler.h:22:
In file included from /usr/include/Foundation/Foundation.h:50:
In file included from /usr/include/Foundation/NSClassDescription.h:30:
/usr/include/Foundation/NSException.h:44:2: error: "There are two separate exception handling mechanisms available ... one based on the standard setjmp() function
      (which does not require special compiler support), and one 'native' version where the compiler manages the exception handling. If you try to use both in the same executable,
      exception handlers will not work... which can be pretty disastrous. This error is telling you that the gnustep-base library was built using one form of exception handling,
      but that the gnustep-make package you are using is building code to use the other form of exception handling ... with the consequence that exception handling would be broken
      in the program you are building. So, somehow your gnustep-base and gnustep-make package are incompatible, and you need to replace one of them with a version configured to
      match the other."
#error "There are two separate exception handling mechanisms available ... one based on the standard setjmp() function (which does not require special compiler support), an...
 ^
/usr/include/Foundation/NSException.h:48:2: error: "gnustep-base is configured to use 'traditional' exceptions, but you are building for 'native' exceptions."
#error  "gnustep-base is configured to use 'traditional' exceptions, but you are building for 'native' exceptions."
 ^
2 errors generated.
/usr/share/GNUstep/Makefiles/rules.make:479: recipe for target 'obj/UnitKit.obj/FrameworkSource/UKTestHandler.m.o' failed
make[4]: *** [obj/UnitKit.obj/FrameworkSource/UKTestHandler.m.o] Error 1
/usr/share/GNUstep/Makefiles/Instance/framework.make:611: recipe for target 'internal-framework-run-compile-submake' failed
make[3]: *** [internal-framework-run-compile-submake] Error 2
/usr/share/GNUstep/Makefiles/Master/rules.make:311: recipe for target 'UnitKit.all.framework.variables' failed
make[2]: *** [UnitKit.all.framework.variables] Error 2
/usr/share/GNUstep/Makefiles/Master/serial-subdirectories.make:53: recipe for target 'internal-all' failed
make[1]: *** [internal-all] Error 2
/usr/share/GNUstep/Makefiles/Master/serial-subdirectories.make:53: recipe for target 'internal-all' failed
make: *** [internal-all] Error 2

**Comment by qmathe** [comment]
Hi,

Looks like your gnustep-make and gnustep-base installs are not compatible. You need to reinstall them and/or change how you configured their exception support.

You should probably to reconfigure GNUstep Base with 'native exceptions' support.

If the issue persists, send a mail to discuss-gnustep@gnu.org or open an issue on GNUstep bug tracker.
